name: 2ndpractice github
on: 
 pull_request:
  types:
  - opened
 push:
  branches:
   - main
jobs:
 test_expression:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: log expression
     run: echo "${{ toJSON(github.event) }}"
   - name: print message
     run: echo "hello world"
   - name: install dependencies
     run: cd ecomm-react-app && npm install
   - name: build Project
     run: cd ecomm-react-app && npm run build
   - name: download articraft
     uses: actions/upload-artifact@v4
     with:
      name: React-buil-artifact
      path: ecomm-react-app/dist/
#  deploy:
#   needs: test_expression
#   runs-on: ubuntu-latest
#   steps:
#   - name: download-artifact
#     uses: actions/download-artifact@v4
#     with:
#      name: React-buil-artifact
#      path: /artifacts
  
    
