name: first CI Job
on: workflow_dispatch
jobs:
 firstjob:
  runs-on: ubuntu-latest
  steps:
   - name: print-greeting
     run: echo "hello world!"
   - name: Print goodbye
     run: echo "goodbye"
 secondjob:
  runs-on: ubuntu-latest
  steps:
   - name: printgreeting
     run: echo "new job"
